services:
  frontend:
    container_name: osint-toolkit-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_BACKEND_API=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - osint-toolkit-network

  backend:
    container_name: osint-toolkit-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - GHUNT_CREDS_DATA=b64_credentials # retrieved in ~/.malfrats/ghunt/creds.m 
    environment:
      - REDDIT_CLIENT_ID=1234
      - REDDIT_CLIENT_SECRET=1234
    ports:
      - "5000:5000"
    networks:
      - osint-toolkit-network

networks:
  osint-toolkit-network:
    driver: bridge
